version: '3'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: "UCWeb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres1"
    ports:
      - "5432"


  api:
    build: ./api
    environment:
      PORT: 6000
      BASE_URL: "http://localhost"
      DB_NAME: "UCWeb"
      PSQL_USER: "postgres"
      PSQL_PASS: "postgres1"
      DB_HOST: db
    ports:
      - "6000:6000"
    volumes:
      # - ./api/models:/api-test/models
      # - ./api/controllers:/api-test/controllers
      # - ./api/routes:/api-test/routes 
      # - ./api/config:/api-test/config
      - ./api/:/api
    depends_on:
      - db

  client:
    build: ./client
    environment:
      PORT: 3031
    ports:
      - "3031:3031"
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src
